modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
[[mods]]
modId="wysicraft"
version="1.4.0"
displayName="WYSICRAFT Runtime"
description='''Portable, visual Minecraft user interfaces with server-authoritative actions.'''
[[dependencies.wysicraft]]
modId="neoforge"
type="required"
versionRange="[21.1.250,)"
ordering="NONE"
side="BOTH"
[[dependencies.wysicraft]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

